import {
    TurnOverDetail,
    TurnOverGoalDetail,
    TurnOverChallengeDetail,
    TurnOverRetrospectiveDetail,
    ApplicationStage_ApplicationStageStatus,
    Attachment_AttachmentType,
    Attachment_AttachmentCategory,
    Attachment_AttachmentTargetType,
    Memo_MemoTargetType,
    TurnOverRetrospectiveDetail_EmploymentType,
    JobApplication_JobApplicationStatus,
} from "@workfolio/shared/generated/common";
import { createSampleWorker } from "./sampleCareerData";

// 샘플 이직 활동 1: 진행 중 (목표만 설정)
export const createSampleTurnOver1 = (): TurnOverDetail => {
    const now = Date.now();
    const worker = createSampleWorker();

    const turnOverGoal: TurnOverGoalDetail = {
        id: "turn-over-goal-1",
        reason: "현재 회사에서 더 이상의 성장 기회가 보이지 않아 새로운 도전을 하고자 합니다. 특히 대규모 서비스를 기획하고 운영하는 경험과 프로덕트 기획에 대한 깊은 이해를 쌓고 싶습니다.",
        goal: "연봉 1억 이상, 대규모 서비스를 운영하는 글로벌 기업에서 시니어 기획자로 근무하고 싶습니다. 서비스 기획과 프로덕트 기획을 통해 사용자 경험을 개선하고 비즈니스 성장에 기여하고 싶습니다.",
        selfIntroductions: [
            {
                id: "self-intro-1-1",
                question: "본인의 강점과 약점은 무엇인가요?",
                content:
                    "저의 가장 큰 강점은 문제 해결 능력입니다. 복잡한 기술적 문제를 체계적으로 분석하고, 여러 해결 방안을 비교하여 최적의 솔루션을 제시할 수 있습니다. 또한 새로운 기술을 빠르게 학습하고 적용하는 능력이 뛰어납니다.\n\n약점으로는 완벽주의 성향이 있어 때로는 과도하게 세부사항에 집중하는 경향이 있습니다. 이를 개선하기 위해 적절한 우선순위 설정과 데드라인 관리를 연습하고 있습니다.",
                isVisible: true,
                priority: 0,
                createdAt: now - 10 * 24 * 60 * 60 * 1000,
                updatedAt: now - 10 * 24 * 60 * 60 * 1000,
            },
            {
                id: "self-intro-1-2",
                question: "지원 동기를 말씀해 주세요.",
                content:
                    "귀사의 기술 블로그와 오픈소스 기여 활동을 보고 큰 감명을 받았습니다. 특히 대규모 트래픽 처리와 MSA 전환 사례를 읽으면서, 이런 환경에서 일하며 성장하고 싶다는 생각을 했습니다.\n\n또한 귀사의 수평적인 조직 문화와 기술 중심의 의사결정 방식이 저의 가치관과 잘 맞다고 생각합니다. 이러한 환경에서 제 역량을 최대한 발휘하고, 팀과 함께 성장하고 싶습니다.",
                isVisible: true,
                priority: 1,
                createdAt: now - 9 * 24 * 60 * 60 * 1000,
                updatedAt: now - 9 * 24 * 60 * 60 * 1000,
            },
        ],
        interviewQuestions: [
            {
                id: "interview-q-1-1",
                question: "서비스 기획 프로세스에 대해 설명해 주세요.",
                answer: "서비스 기획은 사용자 니즈를 파악하고 비즈니스 목표를 달성하기 위한 솔루션을 설계하는 과정입니다.\n\n주요 프로세스:\n1. 문제 정의: 사용자 페인포인트와 비즈니스 목표 파악\n2. 리서치: 사용자 인터뷰, 경쟁사 분석, 데이터 분석\n3. 솔루션 설계: 기능 명세서 작성, 프로토타입 설계\n4. 검증: 사용자 테스트, A/B 테스트를 통한 검증\n5. 실행: 개발팀과 협업하여 기능 구현\n\n실무에서는 이해관계자 관리, 우선순위 설정, 데이터 기반 의사결정 등을 고려하여 기획합니다.",
                isVisible: true,
                priority: 0,
                createdAt: now - 8 * 24 * 60 * 60 * 1000,
                updatedAt: now - 8 * 24 * 60 * 60 * 1000,
            },
            {
                id: "interview-q-1-2",
                question: "서비스 성장을 위한 기획 전략은 무엇인가요?",
                answer: "서비스 성장을 위한 주요 기획 전략:\n\n1. 사용자 리서치: 정기적인 사용자 인터뷰와 설문을 통한 니즈 파악\n2. 데이터 분석: 사용자 행동 데이터 분석을 통한 인사이트 도출\n3. A/B 테스트: 다양한 기획안을 테스트하여 최적의 솔루션 도출\n4. 로드맵 수립: 단기/중기/장기 목표를 설정하고 우선순위 관리\n5. 경쟁사 분석: 시장 트렌드와 경쟁사 동향 파악\n6. 성장 지표 설정: 핵심 지표(KPI)를 설정하고 모니터링\n\n실제로 이전 회사에서 사용자 리서치와 A/B 테스트를 통해 주요 기능의 사용률을 40% 향상시킨 경험이 있습니다.",
                isVisible: true,
                priority: 1,
                createdAt: now - 7 * 24 * 60 * 60 * 1000,
                updatedAt: now - 7 * 24 * 60 * 60 * 1000,
            },
        ],
        checkList: [
            {
                id: "checklist-1-1",
                checked: true,
                content: "이력서 최신화 완료",
                isVisible: true,
                priority: 0,
                createdAt: now - 15 * 24 * 60 * 60 * 1000,
                updatedAt: now - 15 * 24 * 60 * 60 * 1000,
            },
            {
                id: "checklist-1-2",
                checked: true,
                content: "포트폴리오 사이트 업데이트",
                isVisible: true,
                priority: 1,
                createdAt: now - 14 * 24 * 60 * 60 * 1000,
                updatedAt: now - 14 * 24 * 60 * 60 * 1000,
            },
            {
                id: "checklist-1-3",
                checked: false,
                content: "포트폴리오 정리",
                isVisible: true,
                priority: 2,
                createdAt: now - 13 * 24 * 60 * 60 * 1000,
                updatedAt: now - 13 * 24 * 60 * 60 * 1000,
            },
            {
                id: "checklist-1-4",
                checked: false,
                content: "기획 사례 블로그 글 작성",
                isVisible: true,
                priority: 3,
                createdAt: now - 12 * 24 * 60 * 60 * 1000,
                updatedAt: now - 12 * 24 * 60 * 60 * 1000,
            },
        ],
        memos: [
            {
                id: "memo-1-1",
                content:
                    "네이버, 카카오, 쿠팡, 배달의민족, 당근마켓 등 대규모 서비스 기업의 기획자 포지션 중심으로 지원 예정",
                targetId: "turn-over-goal-1",
                targetType: Memo_MemoTargetType.TURN_OVER_GOAL,
                isVisible: true,
                priority: 0,
                createdAt: now - 11 * 24 * 60 * 60 * 1000,
                updatedAt: now - 11 * 24 * 60 * 60 * 1000,
            },
            {
                id: "memo-1-2",
                content: "프로덕트 매니저 자격증 취득 고려 중",
                targetId: "turn-over-goal-1",
                targetType: Memo_MemoTargetType.TURN_OVER_GOAL,
                isVisible: true,
                priority: 1,
                createdAt: now - 10 * 24 * 60 * 60 * 1000,
                updatedAt: now - 10 * 24 * 60 * 60 * 1000,
            },
        ],
        attachments: [
            {
                id: "attachment-1-1",
                type: Attachment_AttachmentType.RESUME,
                category: Attachment_AttachmentCategory.FILE,
                url: "",
                fileName: "홍길동_이력서_2024.pdf",
                fileUrl: "https://example.com/resumes/hong-2024.pdf",
                targetId: "turn-over-goal-1",
                targetType: Attachment_AttachmentTargetType.ENTITY_TURN_OVER_GOAL,
                isVisible: true,
                priority: 0,
                createdAt: now - 15 * 24 * 60 * 60 * 1000,
                updatedAt: now - 15 * 24 * 60 * 60 * 1000,
            },
            {
                id: "attachment-1-2",
                type: Attachment_AttachmentType.PORTFOLIO,
                category: Attachment_AttachmentCategory.URL,
                url: "https://portfolio.hong.com",
                fileName: "",
                fileUrl: "",
                targetId: "turn-over-goal-1",
                targetType: Attachment_AttachmentTargetType.ENTITY_TURN_OVER_GOAL,
                isVisible: true,
                priority: 1,
                createdAt: now - 14 * 24 * 60 * 60 * 1000,
                updatedAt: now - 14 * 24 * 60 * 60 * 1000,
            },
        ],
        createdAt: now - 20 * 24 * 60 * 60 * 1000,
        updatedAt: now - 7 * 24 * 60 * 60 * 1000,
    };

    // 진행 중: 지원 기록 5개, 회고 없음
    const turnOverChallenge: TurnOverChallengeDetail = {
        id: "turn-over-challenge-1",
        jobApplications: [
            {
                id: "job-app-1-1",
                name: "네이버",
                position: "시니어 기획자",
                jobPostingTitle: "네이버 서비스 기획팀 시니어 기획자",
                jobPostingUrl: "https://recruit.navercorp.com/naver/job/detail/12345",
                startedAt: now - 20 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PENDING,
                applicationSource: "원티드",
                memo: "대규모 서비스 기획 경험 어필",
                isVisible: true,
                priority: 0,
                applicationStages: [
                    {
                        id: "app-stage-1-1-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PENDING,
                        startedAt: now - 20 * 24 * 60 * 60 * 1000,
                        memo: "서류 제출 완료",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 20 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 20 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 20 * 24 * 60 * 60 * 1000,
                updatedAt: now - 20 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-1-2",
                name: "카카오",
                position: "기획자",
                jobPostingTitle: "카카오페이 서비스 기획자",
                jobPostingUrl: "https://careers.kakao.com/jobs/P-12345",
                startedAt: now - 18 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PASSED,
                applicationSource: "사람인",
                memo: "결제 서비스 기획 경험 어필",
                isVisible: true,
                priority: 1,
                applicationStages: [
                    {
                        id: "app-stage-1-2-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 18 * 24 * 60 * 60 * 1000,
                        memo: "서류 합격",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 18 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 15 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-1-2-2",
                        name: "1차 면접",
                        status: ApplicationStage_ApplicationStageStatus.SCHEDULED,
                        startedAt: now + 5 * 24 * 60 * 60 * 1000,
                        memo: "다음 주 면접 예정",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 15 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 18 * 24 * 60 * 60 * 1000,
                updatedAt: now - 1 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-1-3",
                name: "토스",
                position: "기획자",
                jobPostingTitle: "토스뱅크 서비스 기획자 (Senior)",
                jobPostingUrl: "https://toss.im/career/job-detail?gh_jid=5678901",
                startedAt: now - 15 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PENDING,
                applicationSource: "원티드",
                memo: "토스 서비스 기획 사례를 보고 매우 매력적으로 느꼈음",
                isVisible: true,
                priority: 2,
                applicationStages: [
                    {
                        id: "app-stage-1-3-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PENDING,
                        startedAt: now - 15 * 24 * 60 * 60 * 1000,
                        memo: "서류 제출 완료",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 15 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 15 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 15 * 24 * 60 * 60 * 1000,
                updatedAt: now - 15 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-1-4",
                name: "쿠팡",
                position: "Product Manager",
                jobPostingTitle: "Product Manager - Logistics",
                jobPostingUrl: "https://www.coupang.jobs/kr/jobs/12345",
                startedAt: now - 12 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PASSED,
                applicationSource: "링크드인",
                memo: "영어 면접 준비 필요",
                isVisible: true,
                priority: 3,
                applicationStages: [
                    {
                        id: "app-stage-1-4-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 12 * 24 * 60 * 60 * 1000,
                        memo: "서류 합격",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 12 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 10 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-1-4-2",
                        name: "기획 과제",
                        status: ApplicationStage_ApplicationStageStatus.SCHEDULED,
                        startedAt: now + 3 * 24 * 60 * 60 * 1000,
                        memo: "서비스 기획 과제 제출 예정",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 10 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 12 * 24 * 60 * 60 * 1000,
                updatedAt: now - 1 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-1-5",
                name: "배달의민족",
                position: "기획자",
                jobPostingTitle: "배달의민족 서비스 기획자",
                jobPostingUrl: "https://careers.baemin.com/jobs/12345",
                startedAt: now - 10 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PENDING,
                applicationSource: "원티드",
                memo: "대규모 서비스 기획 경험 강조",
                isVisible: true,
                priority: 4,
                applicationStages: [
                    {
                        id: "app-stage-1-5-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PENDING,
                        startedAt: now - 10 * 24 * 60 * 60 * 1000,
                        memo: "서류 제출 완료",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 10 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 10 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 10 * 24 * 60 * 60 * 1000,
                updatedAt: now - 10 * 24 * 60 * 60 * 1000,
            },
        ],
        memos: [],
        attachments: [],
        createdAt: now - 20 * 24 * 60 * 60 * 1000,
        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
    };

    return {
        id: "turn-over-1",
        name: "2024년 하반기 이직",
        startedAt: now - 20 * 24 * 60 * 60 * 1000,
        endedAt: now - 10 * 24 * 60 * 60 * 1000,
        worker,
        turnOverGoal,
        turnOverChallenge,
        turnOverRetrospective: undefined,
        createdAt: now - 20 * 24 * 60 * 60 * 1000,
        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
    };
};

// 샘플 이직 활동 2: 완료 (목표 + 도전 + 회고)
export const createSampleTurnOver2 = (): TurnOverDetail => {
    const now = Date.now();
    const worker = createSampleWorker();

    const turnOverGoal: TurnOverGoalDetail = {
        id: "turn-over-goal-2",
        reason: "현재 회사에서 서비스 기획의 폭이 제한적이어서 더 다양한 서비스를 기획하고 싶습니다. 프로덕트 기획에 집중할 수 있는 환경에서 일하고 싶습니다.",
        goal: "연봉 9000만원 이상, 프로덕트 기획을 중시하는 스타트업에서 리드 기획자로 성장하고 싶습니다.",
        selfIntroductions: [],
        interviewQuestions: [],
        checkList: [],
        memos: [],
        attachments: [],
        createdAt: now - 60 * 24 * 60 * 60 * 1000,
        updatedAt: now - 30 * 24 * 60 * 60 * 1000,
    };

    const turnOverChallenge: TurnOverChallengeDetail = {
        id: "turn-over-challenge-2",
        jobApplications: [
            {
                id: "job-app-2-1",
                name: "토스",
                position: "기획자",
                jobPostingTitle: "토스뱅크 서비스 기획자 (Senior)",
                jobPostingUrl: "https://toss.im/career/job-detail?gh_jid=5678901",
                startedAt: now - 30 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PASSED,
                applicationSource: "원티드",
                memo: "토스 서비스 기획 사례를 보고 매우 매력적으로 느꼈음. 연봉 협상 가능성 높음",
                isVisible: true,
                priority: 0,
                applicationStages: [
                    {
                        id: "app-stage-2-1-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 30 * 24 * 60 * 60 * 1000,
                        memo: "빠르게 서류 합격 통보 받음",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 30 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 28 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-2-1-2",
                        name: "1차 코딩 테스트",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 25 * 24 * 60 * 60 * 1000,
                        memo: "기획 과제 4개 중 3개 완료. 시간 부족했지만 합격",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 28 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 23 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-2-1-3",
                        name: "2차 기술 면접",
                        status: ApplicationStage_ApplicationStageStatus.SCHEDULED,
                        startedAt: now + 3 * 24 * 60 * 60 * 1000,
                        memo: "다음 주 화요일 오후 2시 예정. 서비스 기획과 프로덕트 기획 관련 질문 예상",
                        isVisible: true,
                        priority: 2,
                        createdAt: now - 23 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 30 * 24 * 60 * 60 * 1000,
                updatedAt: now - 1 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-2-2",
                name: "카카오",
                position: "기획자",
                jobPostingTitle: "카카오페이 서비스 기획자",
                jobPostingUrl: "https://careers.kakao.com/jobs/P-12345",
                startedAt: now - 28 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PASSED,
                applicationSource: "사람인",
                memo: "결제 서비스 기획 경험 어필. 대규모 서비스 기획 경험 강조",
                isVisible: true,
                priority: 1,
                applicationStages: [
                    {
                        id: "app-stage-2-2-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 28 * 24 * 60 * 60 * 1000,
                        memo: "2주 후에 서류 합격 통보",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 28 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 14 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-2-2-2",
                        name: "1차 전화 면접",
                        status: ApplicationStage_ApplicationStageStatus.PENDING,
                        startedAt: now - 10 * 24 * 60 * 60 * 1000,
                        memo: "30분간 진행. 서비스 기획 경험 위주로 질문. 분위기 좋았음",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 14 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 10 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 28 * 24 * 60 * 60 * 1000,
                updatedAt: now - 10 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-2-3",
                name: "쿠팡",
                position: "Product Manager",
                jobPostingTitle: "Product Manager - Logistics",
                jobPostingUrl: "https://www.coupang.jobs/kr/jobs/12345",
                startedAt: now - 25 * 24 * 60 * 60 * 1000,
                endedAt: now - 5 * 24 * 60 * 60 * 1000,
                status: JobApplication_JobApplicationStatus.FAILED,
                applicationSource: "링크드인",
                memo: "영어 면접 있음. 물류 서비스 기획 경험 부족해서 불합격",
                isVisible: true,
                priority: 2,
                applicationStages: [
                    {
                        id: "app-stage-2-3-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 25 * 24 * 60 * 60 * 1000,
                        memo: "빠른 서류 합격",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 25 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 23 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-2-3-2",
                        name: "기획 과제",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 20 * 24 * 60 * 60 * 1000,
                        memo: "서비스 기획 과제 제출. 3개 과제 모두 완료",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 23 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 18 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-2-3-3",
                        name: "기획 면접",
                        status: ApplicationStage_ApplicationStageStatus.FAILED,
                        startedAt: now - 10 * 24 * 60 * 60 * 1000,
                        memo: "영어 면접. 서비스 기획 경험 부족으로 불합격. 아쉬움",
                        isVisible: true,
                        priority: 2,
                        createdAt: now - 18 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 5 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 25 * 24 * 60 * 60 * 1000,
                updatedAt: now - 5 * 24 * 60 * 60 * 1000,
            },
        ],
        memos: [
            {
                id: "memo-2-1",
                content:
                    "토스 면접 준비: 금융 서비스 기획 지식, 프로덕트 기획 경험, 서비스 기획 사례 정리",
                targetId: "turn-over-challenge-2",
                targetType: Memo_MemoTargetType.TURN_OVER_CHALLENGE,
                isVisible: true,
                priority: 0,
                createdAt: now - 2 * 24 * 60 * 60 * 1000,
                updatedAt: now - 2 * 24 * 60 * 60 * 1000,
            },
            {
                id: "memo-2-2",
                content: "카카오 결과 기다리는 중. 2주 안에 연락 온다고 함",
                targetId: "turn-over-challenge-2",
                targetType: Memo_MemoTargetType.TURN_OVER_CHALLENGE,
                isVisible: true,
                priority: 1,
                createdAt: now - 10 * 24 * 60 * 60 * 1000,
                updatedAt: now - 10 * 24 * 60 * 60 * 1000,
            },
        ],
        attachments: [],
        createdAt: now - 30 * 24 * 60 * 60 * 1000,
        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
    };

    const turnOverRetrospective: TurnOverRetrospectiveDetail = {
        id: "turn-over-retrospective-2",
        name: "토스",
        salary: 9500,
        position: "기획자",
        jobTitle: "기획팀",
        rank: "시니어",
        department: "금융서비스개발본부",
        reason: "핀테크 분야에서 최신 기술을 접하고, 빠르게 성장하는 환경에서 일하고 싶었습니다.",
        score: 5,
        reviewSummary:
            "매우 만족스러운 이직이었습니다.\n\n장점:\n- 다양한 서비스 기획 경험 (금융, 결제, 투자 등)\n- 대규모 서비스 기획 경험 (사용자 수백만 명)\n- 우수한 동료들과 협업\n- 수평적인 조직 문화\n- 탁월한 복지 (점심/저녁 제공, 넉넉한 휴가)\n- 좋은 연봉과 스톡옵션\n\n아쉬운 점:\n- 초기 온보딩 기간이 짧아서 적응에 시간이 필요했음\n- 금융 도메인 지식을 새로 배워야 했음\n\n전반적으로 기획 역량도 많이 성장하고, 커리어에도 큰 도움이 되는 이직이었습니다.",
        joinedAt: now - 5 * 24 * 60 * 60 * 1000,
        workType: "하이브리드 (주 2일 출근)",
        employmentType: TurnOverRetrospectiveDetail_EmploymentType.FULL_TIME,
        memos: [
            {
                id: "memo-2-retro-1",
                content: "온보딩 프로그램이 잘 되어 있어 적응이 빨랐음",
                targetId: "turn-over-retrospective-2",
                targetType: Memo_MemoTargetType.TURN_OVER_RETROSPECT,
                isVisible: true,
                priority: 0,
                createdAt: now - 4 * 24 * 60 * 60 * 1000,
                updatedAt: now - 4 * 24 * 60 * 60 * 1000,
            },
        ],
        attachments: [],
        createdAt: now - 5 * 24 * 60 * 60 * 1000,
        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
    };

    return {
        id: "turn-over-2",
        name: "2024 상반기 대기업 지원",
        startedAt: now - 20 * 24 * 60 * 60 * 1000,
        endedAt: now - 10 * 24 * 60 * 60 * 1000,
        worker,
        turnOverGoal,
        turnOverChallenge,
        turnOverRetrospective,
        createdAt: now - 60 * 24 * 60 * 60 * 1000,
        updatedAt: now - 1 * 24 * 60 * 60 * 1000,
    };
};

// 샘플 이직 활동 3: 완료 (목표 + 도전 + 회고)
export const createSampleTurnOver3 = (): TurnOverDetail => {
    const now = Date.now();
    const worker = createSampleWorker();

    const turnOverGoal: TurnOverGoalDetail = {
        id: "turn-over-goal-3",
        reason: "스타트업에서 빠르게 성장하는 환경에서 일하고 싶었습니다.",
        goal: "연봉 8000만원, 시리즈 B 이상 스타트업에서 리드 기획자로 근무",
        selfIntroductions: [],
        interviewQuestions: [],
        checkList: [],
        memos: [],
        attachments: [],
        createdAt: now - 180 * 24 * 60 * 60 * 1000,
        updatedAt: now - 150 * 24 * 60 * 60 * 1000,
    };

    const turnOverChallenge: TurnOverChallengeDetail = {
        id: "turn-over-challenge-3",
        jobApplications: [
            {
                id: "job-app-3-1",
                name: "마켓컬리",
                position: "시니어 기획자",
                jobPostingTitle: "컬리 서비스 기획팀 시니어 포지션",
                jobPostingUrl: "https://www.kurly.com/careers/12345",
                startedAt: now - 150 * 24 * 60 * 60 * 1000,
                endedAt: now - 90 * 24 * 60 * 60 * 1000,
                status: JobApplication_JobApplicationStatus.PASSED,
                applicationSource: "원티드",
                memo: "최종 합격! 연봉 협상 성공",
                isVisible: true,
                priority: 0,
                applicationStages: [
                    {
                        id: "app-stage-3-1-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 150 * 24 * 60 * 60 * 1000,
                        memo: "1주일 만에 합격 통보",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 150 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 143 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-3-1-2",
                        name: "기획 과제",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 140 * 24 * 60 * 60 * 1000,
                        memo: "서비스 기획 과제 제출. 3개 과제 모두 완료",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 143 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 138 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-3-1-3",
                        name: "1차 기술 면접",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 130 * 24 * 60 * 60 * 1000,
                        memo: "서비스 기획, 프로젝트 경험 중심. CPO와 리드 기획자 참여",
                        isVisible: true,
                        priority: 2,
                        createdAt: now - 138 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 128 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-3-1-4",
                        name: "2차 컬쳐핏 면접",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 120 * 24 * 60 * 60 * 1000,
                        memo: "VP of Product와 면접. 조직 문화, 협업 방식 논의",
                        isVisible: true,
                        priority: 3,
                        createdAt: now - 128 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 118 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-3-1-5",
                        name: "최종 합격",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 100 * 24 * 60 * 60 * 1000,
                        memo: "연봉 8500만원 제안. 스톡옵션 포함",
                        isVisible: true,
                        priority: 4,
                        createdAt: now - 118 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 100 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 150 * 24 * 60 * 60 * 1000,
                updatedAt: now - 90 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-3-2",
                name: "당근마켓",
                position: "기획자",
                jobPostingTitle: "당근마켓 서비스 기획자",
                jobPostingUrl: "https://www.daangn.com/jobs/12345",
                startedAt: now - 145 * 24 * 60 * 60 * 1000,
                endedAt: now - 110 * 24 * 60 * 60 * 1000,
                status: JobApplication_JobApplicationStatus.FAILED,
                applicationSource: "링크드인",
                memo: "최종 면접까지 갔으나 컬쳐핏에서 아쉽게 탈락",
                isVisible: true,
                priority: 1,
                applicationStages: [
                    {
                        id: "app-stage-3-2-1",
                        name: "서류 전형",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 145 * 24 * 60 * 60 * 1000,
                        memo: "합격",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 145 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 140 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-3-2-2",
                        name: "기획 면접",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 130 * 24 * 60 * 60 * 1000,
                        memo: "기획 역량으로는 좋은 평가",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 140 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 128 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-3-2-3",
                        name: "최종 면접",
                        status: ApplicationStage_ApplicationStageStatus.FAILED,
                        startedAt: now - 115 * 24 * 60 * 60 * 1000,
                        memo: "컬쳐핏 미스매치로 불합격. 피드백: 조직 문화와 맞지 않을 것 같다는 의견",
                        isVisible: true,
                        priority: 2,
                        createdAt: now - 128 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 110 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 145 * 24 * 60 * 60 * 1000,
                updatedAt: now - 110 * 24 * 60 * 60 * 1000,
            },
        ],
        memos: [],
        attachments: [],
        createdAt: now - 150 * 24 * 60 * 60 * 1000,
        updatedAt: now - 90 * 24 * 60 * 60 * 1000,
    };

    const turnOverRetrospective: TurnOverRetrospectiveDetail = {
        id: "turn-over-retrospective-3",
        name: "마켓컬리",
        salary: 8500,
        position: "시니어 기획자",
        jobTitle: "기획팀",
        rank: "시니어",
        department: "개발본부",
        reason: "빠르게 성장하는 커머스 플랫폼에서 대규모 트래픽을 다루고 싶었고, 연봉과 복지 조건도 만족스러웠습니다.",
        score: 4,
        reviewSummary:
            "전반적으로 만족스러운 이직이었습니다.\n\n장점:\n- 다양한 서비스 기획 경험 (커머스, 배송, 마켓플레이스 등)\n- 대규모 서비스 기획 경험 (일 주문 10만 건 이상)\n- 우수한 동료들과 협업\n- 수평적인 조직 문화\n- 좋은 복지 (점심, 저녁 제공, 자유로운 휴가)\n\n아쉬운 점:\n- 초기에는 도메인 이해에 시간이 필요했음\n- 야근이 가끔 있음 (특히 세일 기간)\n\n전반적으로 커리어 성장에 큰 도움이 되는 이직이었고, 기획 역량도 많이 성장할 수 있었습니다.",
        joinedAt: now - 90 * 24 * 60 * 60 * 1000,
        workType: "하이브리드 (주 3일 출근)",
        employmentType: TurnOverRetrospectiveDetail_EmploymentType.FULL_TIME,
        memos: [
            {
                id: "memo-3-1",
                content: "온보딩 프로그램이 잘 되어 있어 적응이 빨랐음",
                targetId: "turn-over-retrospective-3",
                targetType: Memo_MemoTargetType.TURN_OVER_RETROSPECT,
                isVisible: true,
                priority: 0,
                createdAt: now - 80 * 24 * 60 * 60 * 1000,
                updatedAt: now - 80 * 24 * 60 * 60 * 1000,
            },
            {
                id: "memo-3-2",
                content: "입사 3개월 차부터 주요 프로젝트에 리드로 참여",
                targetId: "turn-over-retrospective-3",
                targetType: Memo_MemoTargetType.TURN_OVER_RETROSPECT,
                isVisible: true,
                priority: 1,
                createdAt: now - 60 * 24 * 60 * 60 * 1000,
                updatedAt: now - 60 * 24 * 60 * 60 * 1000,
            },
        ],
        attachments: [
            {
                id: "attachment-3-1",
                type: Attachment_AttachmentType.ETC,
                category: Attachment_AttachmentCategory.FILE,
                url: "",
                fileName: "근로계약서_마켓컬리.pdf",
                fileUrl: "https://example.com/contracts/kurly-2024.pdf",
                targetId: "turn-over-retrospective-3",
                targetType: Attachment_AttachmentTargetType.ENTITY_TURN_OVER_RETROSPECTIVE,
                isVisible: true,
                priority: 0,
                createdAt: now - 90 * 24 * 60 * 60 * 1000,
                updatedAt: now - 90 * 24 * 60 * 60 * 1000,
            },
        ],
        createdAt: now - 90 * 24 * 60 * 60 * 1000,
        updatedAt: now - 30 * 24 * 60 * 60 * 1000,
    };

    return {
        id: "turn-over-3",
        name: "2023 하반기 이커머스 도전",
        startedAt: now - 20 * 24 * 60 * 60 * 1000,
        endedAt: now - 10 * 24 * 60 * 60 * 1000,
        worker,
        turnOverGoal,
        turnOverChallenge,
        turnOverRetrospective,
        createdAt: now - 180 * 24 * 60 * 60 * 1000,
        updatedAt: now - 30 * 24 * 60 * 60 * 1000,
    };
};

// 샘플 이직 활동 4: 완료 (목표 + 도전 + 회고)
export const createSampleTurnOver4 = (): TurnOverDetail => {
    const now = Date.now();
    const worker = createSampleWorker();

    const turnOverGoal: TurnOverGoalDetail = {
        id: "turn-over-goal-4",
        reason: "외국계 기업에서 글로벌 경험을 쌓고 싶습니다.",
        goal: "연봉 1억 2천, 외국계 IT 기업에서 글로벌 팀과 협업하며 프로덕트 기획",
        selfIntroductions: [],
        interviewQuestions: [],
        checkList: [],
        memos: [],
        attachments: [],
        createdAt: now - 45 * 24 * 60 * 60 * 1000,
        updatedAt: now - 40 * 24 * 60 * 60 * 1000,
    };

    const turnOverChallenge: TurnOverChallengeDetail = {
        id: "turn-over-challenge-4",
        jobApplications: [
            {
                id: "job-app-4-1",
                name: "Google Korea",
                position: "Product Manager",
                jobPostingTitle: "Product Manager - Seoul",
                jobPostingUrl: "https://careers.google.com/jobs/12345",
                startedAt: now - 40 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PENDING,
                applicationSource: "LinkedIn",
                memo: "Dream company! 매우 준비 많이 해야 함",
                isVisible: true,
                priority: 0,
                applicationStages: [
                    {
                        id: "app-stage-4-1-1",
                        name: "Resume Screening",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 40 * 24 * 60 * 60 * 1000,
                        memo: "리크루터와 첫 통화 완료",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 40 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 35 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-4-1-2",
                        name: "Phone Interview",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 30 * 24 * 60 * 60 * 1000,
                        memo: "영어로 45분 기획 면접. 서비스 기획과 프로덕트 기획",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 35 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 28 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-4-1-3",
                        name: "Onsite Interview (Virtual)",
                        status: ApplicationStage_ApplicationStageStatus.SCHEDULED,
                        startedAt: now + 7 * 24 * 60 * 60 * 1000,
                        memo: "다음 주 월요일. 5라운드 면접 예정. 서비스 기획 사례와 프로덕트 기획 역량 평가",
                        isVisible: true,
                        priority: 2,
                        createdAt: now - 28 * 24 * 60 * 60 * 1000,
                        updatedAt: now,
                    },
                ],
                createdAt: now - 40 * 24 * 60 * 60 * 1000,
                updatedAt: now,
            },
            {
                id: "job-app-4-2",
                name: "Amazon Korea",
                position: "Product Manager II",
                jobPostingTitle: "Product Manager II - AWS",
                jobPostingUrl: "https://www.amazon.jobs/en/jobs/12345",
                startedAt: now - 35 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PENDING,
                applicationSource: "LinkedIn",
                memo: "AWS 서비스 기획 경험 어필. Leadership Principles 준비 필수",
                isVisible: true,
                priority: 1,
                applicationStages: [
                    {
                        id: "app-stage-4-2-1",
                        name: "Application",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 35 * 24 * 60 * 60 * 1000,
                        memo: "리크루터 연락 받음",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 35 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 30 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-4-2-2",
                        name: "Online Assessment",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 25 * 24 * 60 * 60 * 1000,
                        memo: "기획 과제 + 워크스타일 설문. 2시간 소요",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 30 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 23 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-4-2-3",
                        name: "Technical Phone Screen",
                        status: ApplicationStage_ApplicationStageStatus.PENDING,
                        startedAt: now - 15 * 24 * 60 * 60 * 1000,
                        memo: "1시간 기획 인터뷰. 서비스 기획 케이스 스터디. 어려웠지만 잘 마무리한 것 같음",
                        isVisible: true,
                        priority: 2,
                        createdAt: now - 23 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 15 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 35 * 24 * 60 * 60 * 1000,
                updatedAt: now - 15 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-4-3",
                name: "Microsoft Korea",
                position: "Product Manager",
                jobPostingTitle: "Product Manager - Azure",
                jobPostingUrl: "https://careers.microsoft.com/12345",
                startedAt: now - 32 * 24 * 60 * 60 * 1000,
                endedAt: now - 20 * 24 * 60 * 60 * 1000,
                status: JobApplication_JobApplicationStatus.FAILED,
                applicationSource: "LinkedIn",
                memo: "아쉽게 기획 과제에서 탈락",
                isVisible: true,
                priority: 2,
                applicationStages: [
                    {
                        id: "app-stage-4-3-1",
                        name: "Application",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 32 * 24 * 60 * 60 * 1000,
                        memo: "지원 완료",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 32 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 28 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-4-3-2",
                        name: "Online Assessment",
                        status: ApplicationStage_ApplicationStageStatus.FAILED,
                        startedAt: now - 25 * 24 * 60 * 60 * 1000,
                        memo: "기획 과제 3개 중 2개만 완료. 시간 부족. 불합격",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 28 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 20 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 32 * 24 * 60 * 60 * 1000,
                updatedAt: now - 20 * 24 * 60 * 60 * 1000,
            },
            {
                id: "job-app-4-4",
                name: "Netflix",
                position: "Senior Product Manager",
                jobPostingTitle: "Senior Product Manager - Content Platform",
                jobPostingUrl: "https://jobs.netflix.com/jobs/12345",
                startedAt: now - 20 * 24 * 60 * 60 * 1000,
                endedAt: undefined,
                status: JobApplication_JobApplicationStatus.PENDING,
                applicationSource: "추천",
                memo: "현직자 추천으로 지원. 연봉 매우 높음",
                isVisible: true,
                priority: 3,
                applicationStages: [
                    {
                        id: "app-stage-4-4-1",
                        name: "Referral",
                        status: ApplicationStage_ApplicationStageStatus.PASSED,
                        startedAt: now - 20 * 24 * 60 * 60 * 1000,
                        memo: "대학 선배 추천",
                        isVisible: true,
                        priority: 0,
                        createdAt: now - 20 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 18 * 24 * 60 * 60 * 1000,
                    },
                    {
                        id: "app-stage-4-4-2",
                        name: "Recruiter Call",
                        status: ApplicationStage_ApplicationStageStatus.PENDING,
                        startedAt: now - 15 * 24 * 60 * 60 * 1000,
                        memo: "리크루터와 30분 통화. 매우 긍정적인 분위기",
                        isVisible: true,
                        priority: 1,
                        createdAt: now - 18 * 24 * 60 * 60 * 1000,
                        updatedAt: now - 15 * 24 * 60 * 60 * 1000,
                    },
                ],
                createdAt: now - 20 * 24 * 60 * 60 * 1000,
                updatedAt: now - 15 * 24 * 60 * 60 * 1000,
            },
        ],
        memos: [
            {
                id: "memo-4-1",
                content: "서비스 기획 케이스 스터디 매일 2시간씩. 프로덕트 기획 사례 집중",
                targetId: "turn-over-challenge-4",
                targetType: Memo_MemoTargetType.TURN_OVER_CHALLENGE,
                isVisible: true,
                priority: 0,
                createdAt: now - 40 * 24 * 60 * 60 * 1000,
                updatedAt: now - 40 * 24 * 60 * 60 * 1000,
            },
            {
                id: "memo-4-2",
                content: "영어 면접 준비: 기획 용어 정리, 서비스 기획 경험을 영어로 설명 연습",
                targetId: "turn-over-challenge-4",
                targetType: Memo_MemoTargetType.TURN_OVER_CHALLENGE,
                isVisible: true,
                priority: 1,
                createdAt: now - 35 * 24 * 60 * 60 * 1000,
                updatedAt: now - 35 * 24 * 60 * 60 * 1000,
            },
            {
                id: "memo-4-3",
                content: '프로덕트 기획 준비: "Inspired" 책 읽는 중',
                targetId: "turn-over-challenge-4",
                targetType: Memo_MemoTargetType.TURN_OVER_CHALLENGE,
                isVisible: true,
                priority: 2,
                createdAt: now - 30 * 24 * 60 * 60 * 1000,
                updatedAt: now - 30 * 24 * 60 * 60 * 1000,
            },
        ],
        attachments: [],
        createdAt: now - 40 * 24 * 60 * 60 * 1000,
        updatedAt: now,
    };

    const turnOverRetrospective: TurnOverRetrospectiveDetail = {
        id: "turn-over-retrospective-4",
        name: "Google Korea",
        salary: 12000,
        position: "Product Manager",
        jobTitle: "Product Team",
        rank: "Senior",
        department: "Product",
        reason: "글로벌 기업에서 일하며 최신 기술과 문화를 경험하고 싶었습니다.",
        score: 5,
        reviewSummary:
            "매우 만족스러운 이직이었습니다.\n\n장점:\n- 다양한 글로벌 서비스 기획 경험\n- 글로벌 팀과 협업 경험\n- 우수한 동료들과 협업\n- 수평적인 조직 문화\n- 탁월한 복지 (무료 식사, 헬스케어, 유연한 근무)\n- 매우 좋은 연봉과 스톡옵션\n\n아쉬운 점:\n- 초기 영어 커뮤니케이션에 어려움이 있었음\n- 대규모 조직에서의 프로세스가 복잡함\n\n전반적으로 기획 역량도 많이 성장하고, 글로벌 경험을 쌓을 수 있는 좋은 이직이었습니다.",
        joinedAt: now - 1 * 24 * 60 * 60 * 1000,
        workType: "하이브리드 (주 3일 출근)",
        employmentType: TurnOverRetrospectiveDetail_EmploymentType.FULL_TIME,
        memos: [
            {
                id: "memo-4-retro-1",
                content: "온보딩 프로그램이 매우 잘 되어 있어 적응이 빨랐음",
                targetId: "turn-over-retrospective-4",
                targetType: Memo_MemoTargetType.TURN_OVER_RETROSPECT,
                isVisible: true,
                priority: 0,
                createdAt: now,
                updatedAt: now,
            },
        ],
        attachments: [],
        createdAt: now - 1 * 24 * 60 * 60 * 1000,
        updatedAt: now,
    };

    return {
        id: "turn-over-4",
        name: "2024 외국계 기업 도전",
        startedAt: now - 20 * 24 * 60 * 60 * 1000,
        endedAt: now - 10 * 24 * 60 * 60 * 1000,
        worker,
        turnOverGoal,
        turnOverChallenge,
        turnOverRetrospective,
        createdAt: now - 45 * 24 * 60 * 60 * 1000,
        updatedAt: now,
    };
};

// 샘플 이직 활동 5: 완료 (목표 + 도전 + 회고)
export const createSampleTurnOver5 = (): TurnOverDetail => {
    const now = Date.now();
    const worker = createSampleWorker();

    const turnOverGoal: TurnOverGoalDetail = {
        id: "turn-over-goal-5",
        reason: "일과 삶의 균형을 찾고 싶습니다.",
        goal: "워라밸이 좋은 회사, 연봉 7000만원 이상",
        selfIntroductions: [],
        interviewQuestions: [],
        checkList: [
            {
                id: "checklist-5-1",
                checked: false,
                content: "자기소개서 작성",
                isVisible: true,
                priority: 0,
                createdAt: now - 5 * 24 * 60 * 60 * 1000,
                updatedAt: now - 5 * 24 * 60 * 60 * 1000,
            },
            {
                id: "checklist-5-2",
                checked: false,
                content: "포트폴리오 정리",
                isVisible: true,
                priority: 1,
                createdAt: now - 5 * 24 * 60 * 60 * 1000,
                updatedAt: now - 5 * 24 * 60 * 60 * 1000,
            },
        ],
        memos: [],
        attachments: [],
        createdAt: now - 7 * 24 * 60 * 60 * 1000,
        updatedAt: now - 3 * 24 * 60 * 60 * 1000,
    };

    const turnOverChallenge: TurnOverChallengeDetail = {
        id: "turn-over-challenge-5",
        jobApplications: [],
        memos: [],
        attachments: [],
        createdAt: now - 180 * 24 * 60 * 60 * 1000,
        updatedAt: now - 90 * 24 * 60 * 60 * 1000,
    };

    const turnOverRetrospective: TurnOverRetrospectiveDetail = {
        id: "turn-over-retrospective-5",
        name: "네이버",
        salary: 7500,
        position: "기획자",
        jobTitle: "기획팀",
        rank: "선임",
        department: "개발본부",
        reason: "워라밸이 좋고, 안정적인 환경에서 일하고 싶었습니다.",
        score: 4,
        reviewSummary:
            "만족스러운 이직이었습니다.\n\n장점:\n- 좋은 워라밸 (야근 거의 없음)\n- 안정적인 환경\n- 수평적인 조직 문화\n- 좋은 복지 (점심 제공, 넉넉한 휴가)\n- 적절한 연봉\n\n아쉬운 점:\n- 레거시 서비스가 많아서 새로운 기획을 하기 어려움\n- 대기업 특유의 느린 의사결정\n\n전반적으로 워라밸이 좋고, 안정적인 환경에서 일할 수 있어 만족스러운 이직이었습니다.",
        joinedAt: now - 90 * 24 * 60 * 60 * 1000,
        workType: "하이브리드 (주 2일 출근)",
        employmentType: TurnOverRetrospectiveDetail_EmploymentType.FULL_TIME,
        memos: [
            {
                id: "memo-5-retro-1",
                content: "워라밸이 정말 좋아서 만족스러움",
                targetId: "turn-over-retrospective-5",
                targetType: Memo_MemoTargetType.TURN_OVER_RETROSPECT,
                isVisible: true,
                priority: 0,
                createdAt: now - 85 * 24 * 60 * 60 * 1000,
                updatedAt: now - 85 * 24 * 60 * 60 * 1000,
            },
        ],
        attachments: [],
        createdAt: now - 90 * 24 * 60 * 60 * 1000,
        updatedAt: now - 30 * 24 * 60 * 60 * 1000,
    };

    return {
        id: "turn-over-5",
        name: "2025 워라밸 회사 찾기",
        startedAt: now - 20 * 24 * 60 * 60 * 1000,
        endedAt: now - 10 * 24 * 60 * 60 * 1000,
        worker,
        turnOverGoal,
        turnOverChallenge,
        turnOverRetrospective,
        createdAt: now - 180 * 24 * 60 * 60 * 1000,
        updatedAt: now - 30 * 24 * 60 * 60 * 1000,
    };
};

// 모든 샘플 이직 활동을 배열로 반환
export const createAllSampleTurnOvers = (): TurnOverDetail[] => {
    return [
        createSampleTurnOver1(),
        createSampleTurnOver2(),
        createSampleTurnOver3(),
        createSampleTurnOver4(),
        createSampleTurnOver5(),
    ];
};
